---
title: "Team red_flag"
sidebar: false 
---

This is our project webpage.

Please stay tuned to follow our project activities.

This is our template.

# Team Members

1.  [Buse Doğanay](emu-hacettepe-analytics/emu430-fall2023-busedoganay: emu430-fall2023-busedoganay created by GitHub Classroom)

2.  [Görkem Güneş](https://github.com/emu-hacettepe-analytics/emu430-fall2023-goerkemgunes)

3.  [Keziban Uçar](emu-hacettepe-analytics/emu430-fall2023-kezibanucar: emu430-fall2023-kezibanucar created by GitHub Classroom)

4.  [Recai Yiğit Kurular](emu-hacettepe-analytics/emu430-fall2023-yigitkurular: emu430-fall2023-yigitkurular created by GitHub Classroom)

# Project Topic

The project aims to analyze the Consumer Price Index (CPI) data from Turkey and the US, and compare the changes in the main expenditure groups\' weights over time. We will use data visualization and analytical tools to explore the economic and sociological factors influencing inflation in both countries.

# Data Set

The data source is the TUIK page, which provides rate of changes in the consumer price index and indices by main expenditure groups.
